# Generated by Django 6.0.6 on 2026-06-24 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tagsarlavha')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Rasm')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Havola (ixtiyoriy)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Model nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('main_image', models.ImageField(upload_to='cars/', verbose_name='Asosiy rasm')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Narxi (so'm)")),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Eski narx (chegirma uchun)')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('engine', models.CharField(blank=True, max_length=100, verbose_name='Dvigatel')),
                ('transmission', models.CharField(blank=True, max_length=100, verbose_name='Transmissiya')),
                ('fuel_type', models.CharField(blank=True, max_length=100, verbose_name="Yoqilg'i turi")),
                ('seats', models.PositiveSmallIntegerField(default=5, verbose_name="O'rindiqlar soni")),
                ('is_featured', models.BooleanField(default=False, verbose_name="Bosh sahifada ko'rsatish")),
                ('is_new', models.BooleanField(default=False, verbose_name='Yangi model')),
                ('has_discount', models.BooleanField(default=False, verbose_name='Chegirmada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
            ],
            options={
                'verbose_name': 'Diler',
                'verbose_name_plural': 'Dilerlar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Rasm')),
                ('short_text', models.CharField(blank=True, max_length=300, verbose_name='Qisqa matn')),
                ('content', models.TextField(blank=True, verbose_name="To'liq matn")),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.car')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='main.category', verbose_name='Kategoriya'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.SH.')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('is_processed', models.BooleanField(default=False, verbose_name="Ko'rib chiqilgan")),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car', verbose_name='Avtomobil')),
            ],
            options={
                'verbose_name': "So'rov",
                'verbose_name_plural': "So'rovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
